name: isar_graph
description: "Generate diagram from Isar schema file"
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  args: ^2.4.2
  collection: ^1.18.0
  path: ^1.9.0

dev_dependencies:
  test: ^1.25.2

executables:
  isar_graph:
